In [2]:
import pandas as pd
import numpy as np
import optuna
import matplotlib.pyplot as plt
import networkx as nx
import itertools
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from catboost import CatBoostClassifier
import os
import joblib

In [3]:
stage_1_samples = pd.read_csv('../data/cancer/stage_1_prostate_cancer_samples.csv')
stage_1_samples.shape

(173, 2570)

In [4]:
stage_2_samples = pd.read_csv('../data/cancer/stage_2_prostate_cancer_samples.csv')
stage_2_samples.shape

(395, 2570)

In [5]:
combined_dataset = pd.concat([stage_1_samples, stage_2_samples], ignore_index=True)

In [6]:
# Verify and clean the Stage column
print("Unique values in Stage column:", combined_dataset['Stage'].unique())
combined_dataset['Stage'] = combined_dataset['Stage'].str.strip()
combined_dataset['ID_REF'] = np.where(combined_dataset['Stage'] == 'Stage: 1', 0, 1)
combined_dataset['ID_REF'] = np.where(combined_dataset['Stage'] == 'Stage: 2', 1, combined_dataset['ID_REF'])

# Print class distribution to ensure both classes are present
print("Class distribution in ID_REF column:")
print(combined_dataset['ID_REF'].value_counts())


Unique values in Stage column: ['Stage: 1' 'Stage: 2']
Class distribution in ID_REF column:
ID_REF
1    395
0    173
Name: count, dtype: int64


In [7]:
# Define process_data function
def process_data(data, under_sample_factor=None, over_sample_factor=None):
    columns_to_drop = ['Sample_ID', 'Sex', 'Age', 'Stage', 'Disease']
    data = data.drop(columns=columns_to_drop, axis=1)
    
    x = np.array(data.drop(["ID_REF"], axis=1)).astype('float')
    y = np.array(data["ID_REF"]).astype('int')
    feature_names = data.columns[1:]

    if under_sample_factor is not None and isinstance(under_sample_factor, float) and 0 < under_sample_factor <= 1:
        under_sampler = RandomUnderSampler(sampling_strategy=under_sample_factor)
        x, y = under_sampler.fit_resample(x, y)

    if over_sample_factor is not None and isinstance(over_sample_factor, float) and 0 < over_sample_factor <= 1:
        over_sampler = RandomOverSampler(sampling_strategy=over_sample_factor)
        x, y = over_sampler.fit_resample(x, y)

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0, stratify=y)

    scaler = StandardScaler()
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)

    return x_train, x_test, y_train, y_test, feature_names

In [8]:
# Define parameters
feature_selection_num = 500
feature_importance_num = 20
pca_components = 100  # Number of principal components for PCA

# Process data
x_train, x_test, y_train, y_test, feature_names = process_data(combined_dataset)

In [9]:
# Define the objective function for Optuna - SVM
def svm_objective(trial):
    k = feature_selection_num
    
    C = trial.suggest_loguniform('C', 1e-3, 1e3)
    kernel = trial.suggest_categorical('kernel', ['linear', 'poly', 'rbf', 'sigmoid'])
    
    pipe = Pipeline([
        ('skb', SelectKBest(f_classif, k=k)),
        ('pca', PCA(n_components=pca_components)),
        ('estimator', SVC(C=C, kernel=kernel, random_state=0))
    ])
    
    cv = StratifiedKFold(n_splits=5)
    scores = cross_val_score(pipe, x_train, y_train, cv=cv, scoring='accuracy')
    return scores.mean()

In [10]:
def rf_objective(trial):
    k = feature_selection_num
    
    n_estimators = trial.suggest_int('n_estimators', 100, 1000)
    max_depth = trial.suggest_int('max_depth', 2, 32)
    max_features = trial.suggest_categorical('max_features', ['sqrt', 'log2'])
    criterion = trial.suggest_categorical('criterion', ['gini', 'entropy'])
    
    pipe = Pipeline([
        ('skb', SelectKBest(f_classif, k=k)),
        ('pca', PCA(n_components=pca_components)),
        ('estimator', RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, max_features=max_features, criterion=criterion, random_state=0))
    ])
    
    cv = StratifiedKFold(n_splits=5)
    scores = cross_val_score(pipe, x_train, y_train, cv=cv, scoring='accuracy')
    return scores.mean()

In [11]:
def catboost_objective(trial):
    k = feature_selection_num
    
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-3, 1.0)
    depth = trial.suggest_int('depth', 2, 10)
    iterations = trial.suggest_int('iterations', 100, 1000)
    
    pipe = Pipeline([
        ('skb', SelectKBest(f_classif, k=k)),
        ('pca', PCA(n_components=pca_components)),
        ('estimator', CatBoostClassifier(learning_rate=learning_rate, depth=depth, iterations=iterations, verbose=0, random_state=0))
    ])
    
    cv = StratifiedKFold(n_splits=5)
    scores = cross_val_score(pipe, x_train, y_train, cv=cv, scoring='accuracy')
    return scores.mean()

In [12]:
# Function to save study
def save_study(study, filename):
    joblib.dump(study, filename)

# Function to load study
def load_study(filename):
    return joblib.load(filename)

In [13]:
# Optimize hyperparameters using Optuna
svm_study_filename = 'svm_study_s1_s2.pkl'
rf_study_filename = 'rf_study_s1_s2.pkl'
catboost_study_filename = 'catboost_study_s1_s2.pkl'

### Find Hyperparmeters if not trained already

In [14]:
# SVM Hyperparameter Optimization
if os.path.exists(svm_study_filename):
    svm_study = load_study(svm_study_filename)
else:
    svm_study = optuna.create_study(direction='maximize')
    svm_study.optimize(svm_objective, n_trials=50)
    save_study(svm_study, svm_study_filename)

In [15]:
# RF Hyperparameter Optimization
if os.path.exists(rf_study_filename):
    rf_study = load_study(rf_study_filename)
else:
    rf_study = optuna.create_study(direction='maximize')
    rf_study.optimize(rf_objective, n_trials=50)
    save_study(rf_study, rf_study_filename)

In [16]:
# CatBoost Hyperparameter Optimization
if os.path.exists(catboost_study_filename):
    catboost_study = load_study(catboost_study_filename)
else:
    catboost_study = optuna.create_study(direction='maximize')
    catboost_study.optimize(catboost_objective, n_trials=50)
    save_study(catboost_study, catboost_study_filename)

### Print the best trial for each study

For SVM, RF, and Catboost

In [17]:
print("Best SVM trial:")
svm_trial = svm_study.best_trial
print("  Value: ", svm_trial.value)
print("  Params: ")
for key, value in svm_trial.params.items():
    print(f"    {key}: {value}")

Best SVM trial:
  Value:  0.7666178266178265
  Params: 
    C: 0.9591421535647501
    kernel: rbf


In [18]:
print("Best Random Forest trial:")
rf_trial = rf_study.best_trial
print("  Value: ", rf_trial.value)
print("  Params: ")
for key, value in rf_trial.params.items():
    print(f"    {key}: {value}")

Best Random Forest trial:
  Value:  0.7335286935286935
  Params: 
    n_estimators: 254
    max_depth: 25
    max_features: sqrt
    criterion: entropy


In [19]:
print("Best CatBoost trial:")
catboost_trial = catboost_study.best_trial
print("  Value: ", catboost_trial.value)
print("  Params: ")
for key, value in catboost_trial.params.items():
    print(f"    {key}: {value}")

Best CatBoost trial:
  Value:  0.7445665445665446
  Params: 
    learning_rate: 0.2625202727693991
    depth: 6
    iterations: 496


## Train and evaluate the models with the best hyperparameters

In [20]:
# Train and evaluate the models with the best hyperparameters
def train_and_evaluate(pipe, x_train, y_train, x_test, y_test):
    pipe.fit(x_train, y_train)
    y_pred = pipe.predict(x_test)
    print(f'Testing accuracy {accuracy_score(y_test, y_pred)}')
    print(f'Confusion matrix: \n{confusion_matrix(y_test, y_pred)}')

### SVM

In [21]:
best_svm_params = svm_trial.params
svm_pipe = Pipeline([
    ('skb', SelectKBest(f_classif, k=feature_selection_num)),
    ('pca', PCA(n_components=pca_components)),
    ('estimator', SVC(C=best_svm_params['C'], kernel=best_svm_params['kernel'], random_state=0))
])
train_and_evaluate(svm_pipe, x_train, y_train, x_test, y_test)

Testing accuracy 0.7368421052631579
Confusion matrix: 
[[16 19]
 [11 68]]


### Random Forest

In [22]:
best_rf_params = rf_trial.params
rf_pipe = Pipeline([
    ('skb', SelectKBest(f_classif, k=feature_selection_num)),
    ('pca', PCA(n_components=pca_components)),
    ('estimator', RandomForestClassifier(n_estimators=best_rf_params['n_estimators'],
                                         max_depth=best_rf_params['max_depth'],
                                         max_features=best_rf_params['max_features'],
                                         criterion=best_rf_params['criterion'],
                                         random_state=0))
])
train_and_evaluate(rf_pipe, x_train, y_train, x_test, y_test)

Testing accuracy 0.7368421052631579
Confusion matrix: 
[[ 8 27]
 [ 3 76]]


### CatBoost

In [23]:
best_catboost_params = catboost_trial.params
catboost_pipe = Pipeline([
    ('skb', SelectKBest(f_classif, k=feature_selection_num)),
    ('pca', PCA(n_components=pca_components)),
    ('estimator', CatBoostClassifier(learning_rate=best_catboost_params['learning_rate'],
                                     depth=best_catboost_params['depth'],
                                     iterations=best_catboost_params['iterations'],
                                     verbose=0,
                                     random_state=0))
])
train_and_evaluate(catboost_pipe, x_train, y_train, x_test, y_test)

Testing accuracy 0.7280701754385965
Confusion matrix: 
[[13 22]
 [ 9 70]]


In [24]:
# Feature importance and top features can be extracted similarly to the previous script
def get_top_features(pipe, feature_names, top_feature_num):
    if isinstance(pipe.named_steps['estimator'], SVC):
        if pipe.named_steps['estimator'].kernel != 'linear':
            raise ValueError("Feature importance is not available for non-linear SVM kernels.")
        feature_scores = pipe.named_steps['estimator'].coef_[0]
    elif isinstance(pipe.named_steps['estimator'], RandomForestClassifier) or isinstance(pipe.named_steps['estimator'], CatBoostClassifier):
        feature_scores = pipe.named_steps['estimator'].feature_importances_
    features = pipe.named_steps['skb'].get_support(indices=True)
    top_indices = np.argsort(np.abs(feature_scores))[::-1][:top_feature_num]
    top_features = [(feature_names[i], feature_scores[i]) for i in top_indices]
    return top_features

In [25]:
# Get top features for each model
try:
    svm_top_features = get_top_features(svm_pipe, feature_names, feature_importance_num)
    print("Top SVM features:", svm_top_features)
except ValueError as e:
    print("SVM feature extraction error:", e)

rf_top_features = get_top_features(rf_pipe, feature_names, feature_importance_num)
catboost_top_features = get_top_features(catboost_pipe, feature_names, feature_importance_num)

print("Top Random Forest features:", rf_top_features)
print("Top CatBoost features:", catboost_top_features)

SVM feature extraction error: Feature importance is not available for non-linear SVM kernels.
Top Random Forest features: [('hsa-miR-518b', 0.05270127521203342), ('hsa-miR-27a-5p', 0.04261240145637569), ('hsa-miR-498', 0.030741914539255875), ('hsa-miR-491-5p', 0.024037457358697622), ('hsa-miR-1207-3p', 0.018924436409009662), ('hsa-miR-2276-3p', 0.01844129748375117), ('hsa-miR-452-5p', 0.015807170143908703), ('hsa-miR-4285', 0.014945344225796828), ('hsa-miR-1302', 0.014506320991160603), ('hsa-miR-520b', 0.013742420307018242), ('hsa-miR-490-3p', 0.01237206691961422), ('hsa-miR-4424', 0.011354378022077796), ('hsa-miR-1255a', 0.011247349590528156), ('hsa-miR-4715-3p', 0.01112745745146574), ('hsa-miR-8056', 0.010917736879192612), ('hsa-miR-512-3p', 0.010722044262680955), ('hsa-miR-516b-3p, hsa-miR-516a-3p', 0.010709225572280432), ('hsa-miR-506-3p', 0.010700740838210222), ('hsa-miR-1208', 0.010587651252197024), ('hsa-miR-198', 0.010510431138402698)]
Top CatBoost features: [('hsa-miR-27a-5p',

In [26]:
# Compile and print the list of top features
def compile_top_features_list(rf_features, cb_features):
    top_features = rf_features + cb_features
    feature_names = [feature[0] for feature in top_features]
    return '\n'.join(feature_names)

top_features_list = compile_top_features_list(rf_top_features, catboost_top_features)
print(top_features_list)

hsa-miR-518b
hsa-miR-27a-5p
hsa-miR-498
hsa-miR-491-5p
hsa-miR-1207-3p
hsa-miR-2276-3p
hsa-miR-452-5p
hsa-miR-4285
hsa-miR-1302
hsa-miR-520b
hsa-miR-490-3p
hsa-miR-4424
hsa-miR-1255a
hsa-miR-4715-3p
hsa-miR-8056
hsa-miR-512-3p
hsa-miR-516b-3p, hsa-miR-516a-3p
hsa-miR-506-3p
hsa-miR-1208
hsa-miR-198
hsa-miR-27a-5p
hsa-miR-518b
hsa-miR-498
hsa-miR-491-5p
hsa-miR-1207-3p
hsa-miR-1302
hsa-miR-2276-3p
hsa-miR-568
hsa-miR-4424
hsa-miR-451a
hsa-miR-4680-5p
hsa-miR-5583-3p
hsa-miR-548ar-3p
hsa-miR-520b
hsa-miR-579-5p
hsa-miR-548l
hsa-miR-580-5p
hsa-miR-199b-5p
hsa-miR-199a-3p, hsa-miR-199b-3p
hsa-miR-198


In [28]:
# Save top features list to a file using pandas
top_features_df = pd.DataFrame(top_features_list.split('\n'), columns=['Feature'])
top_features_df.to_csv('../GSEA/miRNA/s1_s2_miRNA.csv', index=False)